version: '3.8'
name: twins-dev
services:
  twinfaces:
    image: $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_NAME_TWINFACES:${IMAGE_TAG}
    ports:
      - "10322:80"
    environment:
      NEXT_PUBLIC_TWINS_API_URL: "https://dev-twinfaces.80lvl.build/api"
    restart: always

  twins:
    image: $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_NAME_TWINS:${IMAGE_TAG}
    container_name: twins-core
    environment:
      # - JAVA_OPTS="-Djdk.internal.httpclient.debug=${JAVA_DEBUG}"
      # - JAVA_TOOL_OPTIONS="-Xrunjdwp:transport=dt_socket,address=*:10351,server=y,suspend=n"
      - server.port=80
      - server.servlet.context-path=/api
      - spring.datasource.url=jdbc:postgresql://database/twins
      - spring.datasource.username=twins_user
      - spring.datasource.password=twins_pass
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.flyway.enabled=true
      - spring.flyway.placeholder-replacement=false
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=validate
      - spring.jpa.properties.hibernate.default_schema=public
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.jpa.properties.hibernate.jdbc.batch_size=10
      - spring.jpa.properties.hibernate.order_inserts=true
      - spring.main.allow-circular-references=true
    volumes:
      - ./logs:/opt/twins/logs
    ports:
      - "10321:80"
    restart: always

  database:
    image: postgres:16.3
    ports:
      - "10320:5432"
    restart: always
    volumes:
      - twins-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=twins_user
      - POSTGRES_PASSWORD=twins_pass
      - POSTGRES_DB=twins
volumes:
  twins-db:
