import {
  FeaturerParamType,
  UUID_SCHEMA,
  UUID_SET_SCHEMA,
} from "@/entities/featurer";
import { z, ZodType } from "zod";

export const ParamTypeSchemaMap: Record<FeaturerParamType, ZodType<unknown>> = {
  BOOLEAN: z.boolean(),
  DOUBLE: z.number().multipleOf(0.01),
  INT: z.number().int(),
  STRING: z.string(),
  UUID: UUID_SCHEMA,
  WORD_LIST: z.array(z.string()),
  "STRING:TWINS_TWIN_BASIC_FIELD": z.string(),
  "STRING:TWINS_TWIN_TOUCH_ID": UUID_SCHEMA,
  "UUID:TWINS_DATA_LIST_ID": UUID_SCHEMA,
  "UUID:TWINS_LINK_ID": UUID_SCHEMA,
  "UUID:TWINS_MARKER_ID": UUID_SCHEMA,
  "UUID:TWINS_PERMISSION_ID": UUID_SCHEMA,
  "UUID:TWINS_PERMISSION_SCHEMA_ID": UUID_SCHEMA,
  "UUID:TWINS_TWIN_CLASS_FIELD_ID": UUID_SCHEMA,
  "UUID:TWINS_TWIN_CLASS_ID": UUID_SCHEMA,
  "UUID:TWINS_TWIN_CLASS_SCHEMA_ID": UUID_SCHEMA,
  "UUID:TWINS_TWINFLOW_SCHEMA_ID": UUID_SCHEMA,
  "UUID:TWINS_TWIN_ID": UUID_SCHEMA,
  "UUID:TWINS_TWIN_STATUS_ID": UUID_SCHEMA,
  "UUID_SET:TWINS_LINK_ID": z.array(UUID_SCHEMA),
  "UUID_SET:TWINS_TWIN_CLASS_FIELD_ID": UUID_SET_SCHEMA,
  "UUID_SET:TWINS_TWIN_CLASS_ID": UUID_SET_SCHEMA,
  "UUID_SET:TWINS_TWIN_STATUS_ID": UUID_SET_SCHEMA,
  "UUID_SET:TWINS_USER_GROUP_ID": UUID_SET_SCHEMA,
  "WORD_LIST:TWINS_TWIN_BASIC_FIELD": z.array(z.string()),
} as const;
