import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../styles/globals.css";
import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/ThemeProvider";
import {Toaster} from "sonner";
import {MainLayout} from "@/components/ui/main-layout";

const fontSans = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(
            "min-h-screen fontSans font-sans antialiased",
            fontSans.variable
        )}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <MainLayout>
                {children}
            </MainLayout>

            <Toaster />
        </ThemeProvider>
        </body>
        </html>
    );
}
